name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-expo-android:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Setup Expo CLI
      run: npm install -g @expo/cli eas-cli

    - name: Install dependencies
      run: npm ci

    - name: Setup EAS
      uses: expo/expo-github-action@v8
      with:
        eas-version: latest
        token: ${{ secrets.EXPO_TOKEN }}

    - name: Build Android APK
      run: |
        # Create eas.json if it doesn't exist
        if [ ! -f eas.json ]; then
          cat > eas.json << 'EOF'
        {
          "cli": {
            "version": ">= 3.0.0",
            "appVersionSource": "remote"
          },
          "build": {
            "development": {
              "developmentClient": true,
              "distribution": "internal"
            },
            "preview": {
              "distribution": "internal",
              "android": {
                "buildType": "apk"
              }
            },
            "production": {
              "android": {
                "buildType": "apk",
                "gradleCommand": ":app:assembleRelease"
              }
            }
          }
        }
        EOF
        fi
        
        # Build for production
        eas build --platform android --profile production --non-interactive --wait

    - name: Download and upload artifacts
      run: |
        # Get the latest build URL
        BUILD_URL=$(eas build:list --platform=android --limit=1 --json | jq -r '.[0].artifacts.buildUrl')
        if [ "$BUILD_URL" != "null" ]; then
          curl -L -o android-build.apk "$BUILD_URL"
        fi

    - name: Upload Android build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: expo-android-build
        path: android-build.apk
        retention-days: 30
      if: success()


    - name: Upload artifacts to S3
      if: always()
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: us-east-2
      run: |
        # Upload Expo builds
        if [ -f android-build.apk ]; then
          aws s3 cp android-build.apk s3://mobile-latch/artifacts/${{ github.run_id }}/android-build.apk
        fi
        if [ -f ios-build.tar.gz ]; then
          aws s3 cp ios-build.tar.gz s3://mobile-latch/artifacts/${{ github.run_id }}/ios-build.tar.gz
        fi
        echo "Artifacts uploaded to s3://mobile-latch/artifacts/${{ github.run_id }}/"
